language: php
php:
- 5.3
- 5.6
env:
- DB=mysql
before_script:
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS myapp;" -uroot; fi

before_script: 
- php /home/travis/build/casualuser/Qbix/MyApp/scripts/Q/configure.php
- php /home/travis/build/casualuser/Qbix/MyApp/scripts/Q/install.php --all

script: phpunit -c /home/travis/build/casualuser/Qbix/platform/tests/q.phpunit.xml